# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0002_auto_20170428_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='rank',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sitter_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
