# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0003_auto_20170430_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='ratings_score',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='rank',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='url',
            field=models.SlugField(blank=True),
        ),
    ]
