# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitters', '0004_auto_20170501_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
