# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.IntegerField(blank=True),
        ),
    ]
